[project]
name = "mcp-server-expense-tracker"
version = "0.1.0"
description = "AI-Driven Financial MCP Server (Expense Tracker) "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.5",
]
